name: recycle_this
description: "Spot the specified recycleables. A Hackathon project for Global Gamers Challenge."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flame: ^1.14.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/cans/
    - assets/images/clothes/
    - assets/images/cups/
    - assets/images/electronics/
    - assets/images/furnitures/
    - assets/images/packages/
    - assets/images/papers/
    - assets/images/plastic/
