name: recycle_this
description: "Spot the specified recycleables. A Hackathon project for Global Gamers Challenge."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/fonts/Silkscreen/
    - assets/images/background/
    - assets/images/bottle/
    - assets/images/can/
    - assets/images/clothes/
    - assets/images/cup/
    - assets/images/electronics/
    - assets/images/furniture/
    - assets/images/paper/
    - assets/images/parcel/
    - assets/images/plastic/
    - assets/images/random/

  fonts:
    - family: Silkscreen
      fonts:
        - asset: assets/fonts/Silkscreen/Silkscreen-Regular.ttf

